import type { Metadata } from "next";
import { Inter, Work_Sans } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const work_Sans = Work_Sans({ subsets: ["latin"], weight: ['400', '700'], variable: '--Work-Sans' });

export const metadata: Metadata = {
  title: "AyoDesign",
  description: "Generated by create next app",
  icons: {
    icon: '/assets/logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
